CREATE TABLE [dbo].[Threads]
(
	[Id] NCHAR(128) NOT NULL PRIMARY KEY, 
    [Title] NVARCHAR(512) NOT NULL, 
    [CreateOn] DATETIME NOT NULL,
	[TypeId] INT NULL,
	[ForumId] NCHAR(128) NOT NULL,
	[AuthorId] NCHAR(128) NOT NULL
)

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Tags](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](128) NOT NULL,
	[Description] [nvarchar] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ThreadTags](
	[ThreadId] nchar(128) NOT NULL,
	[TagId] int NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ThreadId], [TagId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO